name: AdminHide
version: 26.2
main: de.adminhide.AdminHide
api-version: '1.20'
description: Admins koennen sich mit /hide komplett verstecken
author: joniiasd201

commands:
  hide:
    description: Verstecke dich komplett
    usage: /hide [list]

permissions:
  adminhide.use:
    description: Nutzung von /hide
    default: op
  adminhide.see:
    description: Versteckte Spieler trotzdem sehen
    default: op
